language: swift
osx_image: xcode9.2
xcode_project: THContentMarkerView.xcodeproj
xcode_scheme: THContentMarkerView
xcode_sdk: iphonesimulator11.2
sudo: required

before_install:
  - brew update

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

script:
  - xcodebuild test -project THContentMarkerView.xcodeproj -scheme THContentMarkerView -configuration Debug -destination "OS=11.2,name=iPhone 8" -sdk iphonesimulator -enableCodeCoverage YES ONLY_ACTIVE_ARCH=NO test

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'THContentMarkerView' -X xcodeplist
