language: swift
osx_image: xcode9.2
xcode_project: THContentMarkerView.xcodeproj
xcode_scheme: THContentMarkerView
xcode_sdk: iphonesimulator11.2
sudo: required

before_install:
  - brew update

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

script:
  - xcodebuild -project THContentMarkerView.xcodeproj -target THContentMarkerView -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'THContentMarkerView' -X xcodeplist
